include:
  - .gitlab-ci.config.yml
  - project: 'data-driven-buying/frontend/ci-templates'
    ref: 'master'
    file:
      - '/k8s/secrets/.k8s.secrets.regcred.yml'

variables:
  APP_NAME: ticking-app

test:
  extends: [.rules-all, .yarn-cache]
  image: registry.gitlab.driverama.com/data-driven-buying/frontend/containers/kubectl-web-build-container:16
  stage: test
  interruptible: true
  cache:
    policy: pull-push
  variables:
    GIT_DEPTH: 0
  before_script:
    - yarn install --immutable
  script:
    - yarn lint

# =====================================
# Preview
# =====================================
preview:
  extends: [.rules-mr, .yarn-cache]
  image: registry.gitlab.driverama.com/data-driven-buying/frontend/containers/kubectl-cleevio-vercel-container:16-slim
  stage: deploy
  needs:
    - test
  interruptible: true
  before_script:
    - yarn install --immutable
    - yarn env --environment development
  script:
    - cleevio-vercel --projectName ticking-app --scope driverama --envFile cleevio-vercel.env --silent
  artifacts:
    reports:
      dotenv: cleevio-vercel.env
  environment:
    name: preview/ticking-app/$CI_COMMIT_REF_SLUG/$CI_COMMIT_SHORT_SHA
    url: $CLEEVIO_VERCEL_DEPLOYMENT_URL
  when: manual

preview-dummy:
  extends: [.rules-mr]
  image: registry.gitlab.driverama.com/data-driven-buying/frontend/containers/kubectl-cleevio-vercel-container:16-slim
  stage: deploy
  needs:
    - test
  script:
    - echo "Workaround for failed pipeline state if preview is not deployed"

# =====================================
# Build Next.js
# =====================================
build-ticking-devel:
  extends: [.rules-devel, .yarn-cache, .build]
  variables:
    ENVIRONMENT: development
  when: always

# =====================================
# Build Docker image
# =====================================
docker-ticking-devel:
  extends: [.rules-devel, .yarn-cache, .docker]
  variables:
    ENVIRONMENT: development
  needs:
    - build-ticking-devel

# =====================================
# Prepare regcred
# =====================================
generate-ticking-regcred-devel:
  extends: .k8s.secrets.regcred
  variables:
    KUBERNETES_NAMESPACE: ticking-web
  needs:
    - docker-ticking-devel
  environment:
    name: development/ticking

# =====================================
# Deploy DEV to k8s
# =====================================
deploy-ticking-devel:
  extends: [.rules-devel, .deploy]
  variables:
    KUBERNETES_NAMESPACE: ticking-web
    KUBERNETES_DEPLOYMENT_NAME: ticking-web
    KUBERNETES_ENV_FILE_PATH: 'env/.env.development'
    KUBERNETES_CONFIG_FOLDER: '.k8s/dev'
  needs:
    - generate-ticking-regcred-devel
  environment:
    name: development/ticking
    url: https://ticking.baas-dev.buywheelz.com/
