import { LovMake } from 'core/api/lov/lovMakes'
import { FilterSelectOption } from '../general/select/FilterSelect.utils'

export interface MakeFilterSelectOption extends FilterSelectOption {
  icon?: string
}

export interface MakeIconsMap {
  [key: LovMake['id']]: string
}

export const makeIconsMap: MakeIconsMap = {
  ABARTH: '/images/brands/IconAbarth.svg',
  AIWAYS: '/images/brands/IconAiways.svg',
  ALFAROMEO: '/images/brands/IconAlfaRomeo.svg',
  ALPINA: '/images/brands/IconAlpina.svg',
  ASTONMARTI: '/images/brands/IconAstonMartin.svg',
  AUDI: '/images/brands/IconAudi.svg',
  BENTLEY: '/images/brands/IconBentley.svg',
  BMW: '/images/brands/IconBMW.svg',
  BUICK: '/images/brands/IconBuick.svg',
  BYTON: '/images/brands/IconByton.svg',
  CADILLAC: '/images/brands/IconCadillac.svg',
  CITROEN: '/images/brands/IconCitroen.svg',
  CUPRA: '/images/brands/IconCupra.svg',
  DACIA: '/images/brands/IconDacia.svg',
  DAIHATSU: '/images/brands/IconDaihatsu.svg',
  DODGE: '/images/brands/IconDodge.svg',
  DONGFENG: '/images/brands/IconDongFeng.svg',
  DS: '/images/brands/IconDs.svg',
  FERRARI: '/images/brands/IconFerrari.svg',
  FIAT: '/images/brands/IconFiat.svg',
  FORD: '/images/brands/IconFord.svg',
  GENESIS: '/images/brands/IconGenesis.svg',
  HONDA: '/images/brands/IconHonda.svg',
  HUMMER: '/images/brands/IconHummer.svg',
  CHEVROLET: '/images/brands/IconChevrolet.svg',
  CHRYSLER: '/images/brands/IconChrysler.svg',
  INFINITI: '/images/brands/IconInfiniti.svg',
  HYUNDAI: '/images/brands/IconHyundai.svg',
  ISUZU: '/images/brands/IconIsuzu.svg',
  IVECO: '/images/brands/IconIveco.svg',
  JAC: '/images/brands/IconJAC.svg',
  JAGUAR: '/images/brands/IconJaguar.svg',
  JEEP: '/images/brands/IconJeep.svg',
  KIA: '/images/brands/IconKia.svg',
  VAZLADA: '/images/brands/IconLada.svg',
  LAMBORGHIN: '/images/brands/IconLamborghini.svg',
  LANCIA: '/images/brands/IconLancia.svg',
  LANDROVER: '/images/brands/IconLandrover.svg',
  LEXUS: '/images/brands/IconLexus.svg',
  LINCOLN: '/images/brands/IconLincoln.svg',
  LYNKCO: '/images/brands/IconLynkCo.svg',
  MASERATI: '/images/brands/IconMaserati.svg',
  MAYBACH: '/images/brands/IconMaybach.svg',
  MAZDA: '/images/brands/IconMazda.svg',
  MCLAREN: '/images/brands/IconMcLaren.svg',
  MERCEDES: '/images/brands/IconMercedes.svg',
  MG: '/images/brands/IconMG.svg',
  MINI: '/images/brands/IconMini.svg',
  MITSUBISHI: '/images/brands/IconMitsubishi.svg',
  NIO: '/images/brands/IconNio.svg',
  NISSAN: '/images/brands/IconNissan.svg',
  OPEL: '/images/brands/IconOpel.svg',
  PEUGEOT: '/images/brands/IconPeugeot.svg',
  POLESTAR: '/images/brands/IconPolestar.svg',
  PORSCHE: '/images/brands/IconPorsche.svg',
  RENAULT: '/images/brands/IconRenault.svg',
  ROLLSROYCE: '/images/brands/IconRollsRoyce.svg',
  SAAB: '/images/brands/IconSaab.svg',
  SEAT: '/images/brands/IconSeat.svg',
  SKODA: '/images/brands/IconSkoda.svg',
  SMART: '/images/brands/IconSmart.svg',
  SSANGYONG: '/images/brands/IconSSangYong.svg',
  SUBARU: '/images/brands/IconSubaru.svg',
  SUZUKI: '/images/brands/IconSuzuki.svg',
  TESLA: '/images/brands/IconTesla.svg',
  TOYOTA: '/images/brands/IconToyota.svg',
  VW: '/images/brands/IconVolkswagen.svg',
  VOLVO: '/images/brands/IconVolvo.svg'
}
