apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-tls
spec:
  secretName: web-tls
  issuerRef:
    name: letsencrypt-dev
    kind: ClusterIssuer
  commonName: ticking.baas-dev.buywheelz.com
  dnsNames:
    - ticking.baas-dev.buywheelz.com
